#!/bin/bash



montableau=("ewok" "kenobi" "Lando" "sodium" "galadriel" "dragon"
            "minotaure"
            "succube"
            "hippogriffe"
            "manticore"
            "cerbere"
            "behemot"
            "gorgone"
            "basilic"
            "hydre"
            "wyvern"
            "troll"
            "gobelin"
            "pixie"
            "nymphe"
            "pegase"
            "phenix"
            "griffon"
            "galium"
            "zirconium"
            "polonium"
            "cobalt"
            "nickel"
            "phosphore"
            "azote"
            "neon"
            "carbone"
            "bore"
            "titane"
            "oxygene"
            "antimoine"
            "iode"
            "sodium"
            "actinium"
            "fluor"
            "uranium"
            "ablette"
            "anguille"
            "brochet"
            "carpe"
            "chevesne"
            "gardon"
            "goujon"
            "omble"
            "perche"
            "tanche"
            "truite"
            "sandre"
            "silure"
            "vairon"
            "maya"
            "goldorak"
            "candy"
            "snorki"
            "albator"
            "bouba"
            "heidi"
            "calimero"
            "casimir"
            "esteban"
            "zia"
            "tao"
            "clementine"
            "diabolo"
            "scoubidou"
            "ladyoscar"
            "alose"
            "bonite"
            "corb"
            "daurade"
            "eperlan"
            "fletan"
            "gobie"
            "mordocet"
            "nerophis"
            "orphie"
            "palomete"
            "rouget"
            "sar"
            "tacaud"
            "luke"
            "leia"
            "r2d2"
            "vador"
            "solo"
            "palpatine"
            "yoda"
            "kenobi"
            "ewok"
            "jabba"
            "chewie"
            "lando"
            "dagobah"
            "bobafett"
            "z6po"
            "ackbar"
            "atkinson"
            "atanasoff"
            "babagge"
            "backus"
            "boole"
            "carmack"
            "colmerauer"
            "dijkstra"
            "gates"
            "gosling"
            "grove"
            "hopper"
            "jobs"
            "kernighan"
            "knuth"
            "liskov"
            "lovelace"
            "moore"
            "murdock"
            "neumann"
            "shannon"
            "stallman"
            "swartz"
            "torvalds"
            "turing"
            "zemanek"
            "angel"
            "banshee"
            "bishop"
            "cable"
            "colossus"
            "cyclope"
            "dazzler"
            "diablo"
            "forge"
            "gambit"
            "havok"
            "iceberg"
            "jeangrey"
            "jubele"
            "magma"
            "magneto"
            "malicia"
            "mystique"
            "polaris"
            "psylocke"
            "rocket"
            "serval"
            "shadowcat"
            "sunfire"
            "tornade"
            "xorn"
            "arryn"
            "baratheon"
            "bravoos"
            "dorne"
            "greyjoy"
            "lannister"
            "marcheursblancs"
            "martell"
            "meeren"
            "portreal"
            "sauvageons"
            "stark"
            "targaryen"
            "tully"
            "tyrell"
            "volantis"
            "winterfell"
            "archimede"
            "aston"
            "copernic"
            "darwin"
            "descartes"
            "edison"
            "einsten"
            "fermat"
            "galilee"
            "hawking"
            "kepler"
            "newton"
            "ohm"
            "pascal"
            "socrate"
            "tesla"
            "volta"
            "watt"
            "apollinaire"
            "baudelaire"
            "brassens"
            "demusset"
            "ferre"
            "gautier"
            "hugo"
            "lafontaine"
            "lamartine"
            "mallarme"
            "maupassant"
            "poe"
            "prevert"
            "rimbaud"
            "sand"
            "verlaine"
            "aragorn"
            "arwen"
            "bilbo"
            "boromir"
            "elrond"
            "eomer"
            "eowyn"
            "faramir"
            "frodon"
            "galadriel"
            "gandalf"
            "gimli"
            "legolas"
            "merry"
            "pippin"
            "sam"
            "aspicot"
            "bulbizarre"
            "carapuce"
            "chenipan"
            "hypotrempe"
            "magicarpe"
            "melofee"
            "nidoran"
            "piafabec"
            "pikachu"
            "psykokwak"
            "rattata"
            "rondoudou"
            "roucool"
            "salameche"
            "taupiqueur"
            "ader"
            "bastie"
            "bleriot"
            "boeing"
            "boucher"
            "farman"
            "garros"
            "guynemer"
            "latecoere"
            "lindbergh"
            "marvingt"
            "mermoz"
            "messerschmitt"
            "saintexupery"
            "voisin"
            "wright"
            "acdc"
            "aerosmith"
            "beatles"
            "clapton"
            "clash"
            "cooper"
            "deeppurple"
            "doors"
            "dylan"
            "eagles"
            "epica"
            "hendrix"
            "kiss"
            "ledzepplin"
            "loureed"
            "motorhead"
            "metallica"
            "muse"
            "pinkfloyd"
            "queen"
            "scorpion"
            "stones"
            "superbus"
            "zztop")



ssh ewok -t "cd /work ;rm -r DataNode*" 

ssh ewok -t "fuser -k 8000/tcp; fuser -k 7000/tcp;cd nosave/hidoop-2/hidoop-2 ;java  hdfs/NameNode" &


for i in {1..5}
do
port=$
ssh Kenobi -t "cd /work ;rm -r DataNode*"

ssh Kenobi -t "fuser -k 8002/tcp;fuser -k 9002/tcp;cd nosave/hidoop-2/hidoop-2 ;java  hdfs/DataNode" &

done

ssh Kenobi -t "cd /work ;rm -r DataNode*"

ssh Kenobi -t "fuser -k 8002/tcp;fuser -k 9002/tcp;cd nosave/hidoop-2/hidoop-2 ;java  hdfs/DataNode" &

ssh Lando -t "cd /work ;rm -r DataNode*" 

ssh Lando -t "fuser -k 8003/tcp;fuser -k 9003/tcp;cd nosave/hidoop-2/hidoop-2 ;java  hdfs/DataNode" &

ssh sodium -t "cd /work ;rm -r DataNode*"

ssh sodium -t "fuser -k 8004/tcp;fuser -k 9004/tcp;cd nosave/hidoop-2/hidoop-2 ;java  hdfs/DataNode" &

ssh galadriel -t "cd /work ;rm -r DataNode*"

ssh galadriel -t "fuser -k 8005/tcp;fuser -k 9005/tcp;cd nosave/hidoop-2/hidoop-2 ;java  hdfs/DataNode" &


